# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accountRecovery.ui'
#
# Created: Mon Mar  9 11:21:33 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AccountRecovery(object):
    def setupUi(self, AccountRecovery):
        AccountRecovery.setObjectName("AccountRecovery")
        AccountRecovery.resize(550, 157)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/quip/Images/quip-bubble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AccountRecovery.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(AccountRecovery)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.centralGridLayout = QtGui.QGridLayout(self.centralwidget)
        self.centralGridLayout.setObjectName("centralGridLayout")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.emailPage = QtGui.QWidget()
        self.emailPage.setObjectName("emailPage")
        self.emailGridLayout = QtGui.QGridLayout(self.emailPage)
        self.emailGridLayout.setHorizontalSpacing(14)
        self.emailGridLayout.setObjectName("emailGridLayout")
        self.unlockLabel = QtGui.QLabel(self.emailPage)
        self.unlockLabel.setText("")
        self.unlockLabel.setPixmap(QtGui.QPixmap(":/quip/Images/recover-unlock-32x32.png"))
        self.unlockLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.unlockLabel.setObjectName("unlockLabel")
        self.emailGridLayout.addWidget(self.unlockLabel, 0, 0, 1, 1)
        self.recoveryLabel = QtGui.QLabel(self.emailPage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.recoveryLabel.setFont(font)
        self.recoveryLabel.setStyleSheet("background")
        self.recoveryLabel.setObjectName("recoveryLabel")
        self.emailGridLayout.addWidget(self.recoveryLabel, 0, 1, 1, 1)
        self.emailLineEdit = QtGui.QLineEdit(self.emailPage)
        self.emailLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.emailLineEdit.setMaxLength(255)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.emailGridLayout.addWidget(self.emailLineEdit, 1, 1, 1, 1)
        self.emailHBoxLayout = QtGui.QHBoxLayout()
        self.emailHBoxLayout.setObjectName("emailHBoxLayout")
        self.emailProgressBar = QtGui.QProgressBar(self.emailPage)
        self.emailProgressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.emailProgressBar.setMaximum(0)
        self.emailProgressBar.setProperty("value", -1)
        self.emailProgressBar.setObjectName("emailProgressBar")
        self.emailHBoxLayout.addWidget(self.emailProgressBar)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.emailHBoxLayout.addItem(spacerItem)
        self.nextButton = QtGui.QPushButton(self.emailPage)
        self.nextButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nextButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/quip/Images/next-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon1)
        self.nextButton.setIconSize(QtCore.QSize(32, 32))
        self.nextButton.setFlat(True)
        self.nextButton.setObjectName("nextButton")
        self.emailHBoxLayout.addWidget(self.nextButton)
        self.emailGridLayout.addLayout(self.emailHBoxLayout, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.emailPage)
        self.codePage = QtGui.QWidget()
        self.codePage.setObjectName("codePage")
        self.recoveryGridLayout = QtGui.QGridLayout(self.codePage)
        self.recoveryGridLayout.setContentsMargins(-1, 11, -1, -1)
        self.recoveryGridLayout.setHorizontalSpacing(14)
        self.recoveryGridLayout.setObjectName("recoveryGridLayout")
        self.recoveryHBoxLayout = QtGui.QHBoxLayout()
        self.recoveryHBoxLayout.setObjectName("recoveryHBoxLayout")
        self.recoveryProgressBar = QtGui.QProgressBar(self.codePage)
        self.recoveryProgressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.recoveryProgressBar.setMaximum(0)
        self.recoveryProgressBar.setProperty("value", -1)
        self.recoveryProgressBar.setObjectName("recoveryProgressBar")
        self.recoveryHBoxLayout.addWidget(self.recoveryProgressBar)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.recoveryHBoxLayout.addItem(spacerItem1)
        self.recoveryButton = QtGui.QPushButton(self.codePage)
        self.recoveryButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.recoveryButton.setIcon(icon1)
        self.recoveryButton.setIconSize(QtCore.QSize(32, 32))
        self.recoveryButton.setFlat(True)
        self.recoveryButton.setObjectName("recoveryButton")
        self.recoveryHBoxLayout.addWidget(self.recoveryButton)
        self.recoveryGridLayout.addLayout(self.recoveryHBoxLayout, 2, 1, 1, 1)
        self.recoveryCodeLineEdit = QtGui.QLineEdit(self.codePage)
        self.recoveryCodeLineEdit.setText("")
        self.recoveryCodeLineEdit.setObjectName("recoveryCodeLineEdit")
        self.recoveryGridLayout.addWidget(self.recoveryCodeLineEdit, 1, 1, 1, 1)
        self.recoveryIconLabel = QtGui.QLabel(self.codePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.recoveryIconLabel.sizePolicy().hasHeightForWidth())
        self.recoveryIconLabel.setSizePolicy(sizePolicy)
        self.recoveryIconLabel.setText("")
        self.recoveryIconLabel.setPixmap(QtGui.QPixmap(":/quip/Images/passphrase.png"))
        self.recoveryIconLabel.setObjectName("recoveryIconLabel")
        self.recoveryGridLayout.addWidget(self.recoveryIconLabel, 0, 0, 1, 1)
        self.codeHBoxLayout = QtGui.QHBoxLayout()
        self.codeHBoxLayout.setObjectName("codeHBoxLayout")
        self.recoveryCodeLabel = QtGui.QLabel(self.codePage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.recoveryCodeLabel.setFont(font)
        self.recoveryCodeLabel.setObjectName("recoveryCodeLabel")
        self.codeHBoxLayout.addWidget(self.recoveryCodeLabel)
        self.helpButton = QtGui.QPushButton(self.codePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButton.sizePolicy().hasHeightForWidth())
        self.helpButton.setSizePolicy(sizePolicy)
        self.helpButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.helpButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/quip/Images/dialog-information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpButton.setIcon(icon2)
        self.helpButton.setFlat(True)
        self.helpButton.setObjectName("helpButton")
        self.codeHBoxLayout.addWidget(self.helpButton)
        self.recoveryGridLayout.addLayout(self.codeHBoxLayout, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.codePage)
        self.phrasePage = QtGui.QWidget()
        self.phrasePage.setObjectName("phrasePage")
        self.gridLayout = QtGui.QGridLayout(self.phrasePage)
        self.gridLayout.setContentsMargins(-1, 11, -1, -1)
        self.gridLayout.setHorizontalSpacing(14)
        self.gridLayout.setObjectName("gridLayout")
        self.passphraseLineEdit = QtGui.QLineEdit(self.phrasePage)
        self.passphraseLineEdit.setMaxLength(32)
        self.passphraseLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passphraseLineEdit.setObjectName("passphraseLineEdit")
        self.gridLayout.addWidget(self.passphraseLineEdit, 1, 1, 1, 1)
        self.passphraseIconLabel = QtGui.QLabel(self.phrasePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passphraseIconLabel.sizePolicy().hasHeightForWidth())
        self.passphraseIconLabel.setSizePolicy(sizePolicy)
        self.passphraseIconLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.passphraseIconLabel.setText("")
        self.passphraseIconLabel.setPixmap(QtGui.QPixmap(":/quip/Images/lock-32x32.png"))
        self.passphraseIconLabel.setObjectName("passphraseIconLabel")
        self.gridLayout.addWidget(self.passphraseIconLabel, 0, 0, 1, 1)
        self.passphraseLabel = QtGui.QLabel(self.phrasePage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passphraseLabel.setFont(font)
        self.passphraseLabel.setObjectName("passphraseLabel")
        self.gridLayout.addWidget(self.passphraseLabel, 0, 1, 1, 1)
        self.phraseHBoxLayout = QtGui.QHBoxLayout()
        self.phraseHBoxLayout.setObjectName("phraseHBoxLayout")
        self.phraseProgressBar = QtGui.QProgressBar(self.phrasePage)
        self.phraseProgressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.phraseProgressBar.setMaximum(0)
        self.phraseProgressBar.setProperty("value", -1)
        self.phraseProgressBar.setObjectName("phraseProgressBar")
        self.phraseHBoxLayout.addWidget(self.phraseProgressBar)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.phraseHBoxLayout.addItem(spacerItem2)
        self.phraseButton = QtGui.QPushButton(self.phrasePage)
        self.phraseButton.setFocusPolicy(QtCore.Qt.TabFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/quip/Images/confirm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.phraseButton.setIcon(icon3)
        self.phraseButton.setIconSize(QtCore.QSize(32, 32))
        self.phraseButton.setFlat(True)
        self.phraseButton.setObjectName("phraseButton")
        self.phraseHBoxLayout.addWidget(self.phraseButton)
        self.gridLayout.addLayout(self.phraseHBoxLayout, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.phrasePage)
        self.centralGridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        AccountRecovery.setCentralWidget(self.centralwidget)

        self.retranslateUi(AccountRecovery)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AccountRecovery)

    def retranslateUi(self, AccountRecovery):
        AccountRecovery.setWindowTitle(QtGui.QApplication.translate("AccountRecovery", "Account Recovery", None, QtGui.QApplication.UnicodeUTF8))
        self.recoveryLabel.setText(QtGui.QApplication.translate("AccountRecovery", "Enter the e-mail registered to your lost account", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLineEdit.setPlaceholderText(QtGui.QApplication.translate("AccountRecovery", "E-mail Address", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("AccountRecovery", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.recoveryButton.setText(QtGui.QApplication.translate("AccountRecovery", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.recoveryCodeLineEdit.setPlaceholderText(QtGui.QApplication.translate("AccountRecovery", "Account Recovery Code", None, QtGui.QApplication.UnicodeUTF8))
        self.recoveryCodeLabel.setText(QtGui.QApplication.translate("AccountRecovery", "Enter your recovery code", None, QtGui.QApplication.UnicodeUTF8))
        self.passphraseLineEdit.setPlaceholderText(QtGui.QApplication.translate("AccountRecovery", "Account passphrase. Minimum 8 characters, maximum 32", None, QtGui.QApplication.UnicodeUTF8))
        self.passphraseLabel.setText(QtGui.QApplication.translate("AccountRecovery", "Enter a new passphrase for the account", None, QtGui.QApplication.UnicodeUTF8))
        self.phraseButton.setText(QtGui.QApplication.translate("AccountRecovery", "Recover", None, QtGui.QApplication.UnicodeUTF8))
        self.phraseButton.setShortcut(QtGui.QApplication.translate("AccountRecovery", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))

from . import quip_qt_rc
