# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emoticons.ui'
#
# Created: Tue Dec 16 15:46:23 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Emoticons(object):
    def setupUi(self, Emoticons):
        Emoticons.setObjectName("Emoticons")
        Emoticons.resize(224, 224)
        Emoticons.setMaximumSize(QtCore.QSize(244, 244))
        Emoticons.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/quip/Images/quip-bubble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Emoticons.setWindowIcon(icon)
        Emoticons.setStyleSheet("background-color: white;")
        self.gridLayout = QtGui.QGridLayout(Emoticons)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.emoticonTable = QtGui.QTableWidget(Emoticons)
        self.emoticonTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.emoticonTable.setFrameShadow(QtGui.QFrame.Plain)
        self.emoticonTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.emoticonTable.setTabKeyNavigation(False)
        self.emoticonTable.setAlternatingRowColors(False)
        self.emoticonTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.emoticonTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.emoticonTable.setTextElideMode(QtCore.Qt.ElideNone)
        self.emoticonTable.setShowGrid(False)
        self.emoticonTable.setObjectName("emoticonTable")
        self.emoticonTable.setColumnCount(7)
        self.emoticonTable.setRowCount(7)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.emoticonTable.setHorizontalHeaderItem(6, item)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/smile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon1)
        item.setToolTip(":smile:")
        self.emoticonTable.setItem(0, 0, item)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/grin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon2)
        item.setToolTip(":grin:")
        self.emoticonTable.setItem(0, 1, item)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/bigsmile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon3)
        item.setToolTip(":bigsmile:")
        self.emoticonTable.setItem(0, 2, item)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/laughing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon4)
        item.setToolTip(":laughing:")
        self.emoticonTable.setItem(0, 3, item)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/laugh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon5)
        item.setToolTip(":laugh:")
        self.emoticonTable.setItem(0, 4, item)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/glasses.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon6)
        item.setToolTip(":glasses:")
        self.emoticonTable.setItem(0, 5, item)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/meh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon7)
        item.setToolTip(":meh:")
        self.emoticonTable.setItem(0, 6, item)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/sad.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon8)
        item.setToolTip(":sad:")
        self.emoticonTable.setItem(1, 0, item)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/crying.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon9)
        item.setToolTip(":crying:")
        self.emoticonTable.setItem(1, 1, item)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/wink.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon10)
        item.setToolTip(":wink:")
        self.emoticonTable.setItem(1, 2, item)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/blush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon11)
        item.setToolTip(":blush:")
        self.emoticonTable.setItem(1, 3, item)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/tounge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon12)
        item.setToolTip(":tounge:")
        self.emoticonTable.setItem(1, 4, item)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/mmm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon13)
        item.setToolTip(":mmm:")
        self.emoticonTable.setItem(1, 5, item)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/whoah.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon14)
        item.setToolTip(":whoah:")
        self.emoticonTable.setItem(1, 6, item)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/tired.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon15)
        item.setToolTip(":tired:")
        self.emoticonTable.setItem(2, 0, item)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/smirk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon16)
        item.setToolTip(":smirk:")
        self.emoticonTable.setItem(2, 1, item)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/woops.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon17)
        item.setToolTip(":woops:")
        self.emoticonTable.setItem(2, 2, item)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/worried.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon18)
        item.setToolTip(":worried:")
        self.emoticonTable.setItem(2, 3, item)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/angry.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon19)
        item.setToolTip(":angry:")
        self.emoticonTable.setItem(2, 4, item)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/devil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon20)
        item.setToolTip(":devil:")
        self.emoticonTable.setItem(2, 5, item)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/pirate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon21)
        item.setToolTip(":pirate:")
        self.emoticonTable.setItem(2, 6, item)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/love.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon22)
        item.setToolTip(":love:")
        self.emoticonTable.setItem(3, 0, item)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/kiss.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon23)
        item.setToolTip(":kiss:")
        self.emoticonTable.setItem(3, 1, item)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/heart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon24)
        item.setToolTip(":heart:")
        self.emoticonTable.setItem(3, 2, item)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/broken.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon25)
        item.setToolTip(":broken:")
        self.emoticonTable.setItem(3, 3, item)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/rose.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon26)
        item.setToolTip(":rose:")
        self.emoticonTable.setItem(3, 4, item)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/wilted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon27)
        item.setToolTip(":wilted:")
        self.emoticonTable.setItem(3, 5, item)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/sick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon28)
        item.setToolTip(":sick:")
        self.emoticonTable.setItem(3, 6, item)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/sleep.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon29)
        item.setToolTip(":sleep:")
        self.emoticonTable.setItem(4, 0, item)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/sleeping.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon30)
        item.setToolTip(":sleeping:")
        self.emoticonTable.setItem(4, 1, item)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/quiet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon31)
        item.setToolTip(":quiet:")
        self.emoticonTable.setItem(4, 2, item)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/ninja.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon32)
        item.setToolTip(":ninja:")
        self.emoticonTable.setItem(4, 3, item)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/clown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon33)
        item.setToolTip(":clown:")
        self.emoticonTable.setItem(4, 4, item)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/angel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon34)
        item.setToolTip(":angel:")
        self.emoticonTable.setItem(4, 5, item)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/cool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon35)
        item.setToolTip(":cool:")
        self.emoticonTable.setItem(4, 6, item)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/hug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon36)
        item.setToolTip(":hug:")
        self.emoticonTable.setItem(5, 0, item)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/hugleft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon37)
        item.setToolTip(":hugleft:")
        self.emoticonTable.setItem(5, 1, item)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon38)
        item.setToolTip(":star:")
        self.emoticonTable.setItem(5, 2, item)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon39)
        item.setToolTip(":blue:")
        self.emoticonTable.setItem(5, 3, item)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/pink.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon40)
        item.setToolTip(":pink:")
        self.emoticonTable.setItem(5, 4, item)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/beer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon41)
        item.setToolTip(":beer:")
        self.emoticonTable.setItem(5, 5, item)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/cocktail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon42)
        item.setToolTip(":cocktail:")
        self.emoticonTable.setItem(5, 6, item)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon43)
        item.setToolTip(":tick:")
        self.emoticonTable.setItem(6, 0, item)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon44)
        item.setToolTip(":cross:")
        self.emoticonTable.setItem(6, 1, item)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon45)
        item.setToolTip(":plus:")
        self.emoticonTable.setItem(6, 2, item)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon46)
        item.setToolTip(":minus:")
        self.emoticonTable.setItem(6, 3, item)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/pizza.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon47)
        item.setToolTip(":pizza:")
        self.emoticonTable.setItem(6, 4, item)
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/cake.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon48)
        item.setToolTip(":cake:")
        self.emoticonTable.setItem(6, 5, item)
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap(":/quip/Images/emoticons/gift.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon49)
        item.setToolTip(":gift:")
        self.emoticonTable.setItem(6, 6, item)
        self.emoticonTable.horizontalHeader().setVisible(False)
        self.emoticonTable.horizontalHeader().setDefaultSectionSize(30)
        self.emoticonTable.horizontalHeader().setMinimumSectionSize(10)
        self.emoticonTable.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.emoticonTable, 0, 0, 1, 1)

        self.retranslateUi(Emoticons)
        QtCore.QMetaObject.connectSlotsByName(Emoticons)

    def retranslateUi(self, Emoticons):
        Emoticons.setWindowTitle(QtGui.QApplication.translate("Emoticons", "Emoticons", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Emoticons", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Emoticons", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Emoticons", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Emoticons", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.verticalHeaderItem(4).setText(QtGui.QApplication.translate("Emoticons", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.verticalHeaderItem(5).setText(QtGui.QApplication.translate("Emoticons", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.verticalHeaderItem(6).setText(QtGui.QApplication.translate("Emoticons", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Emoticons", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Emoticons", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Emoticons", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Emoticons", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Emoticons", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Emoticons", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Emoticons", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.emoticonTable.isSortingEnabled()
        self.emoticonTable.setSortingEnabled(False)
        self.emoticonTable.setSortingEnabled(__sortingEnabled)

from . import quip_qt_rc
