# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'friendList.ui'
#
# Created: Thu Feb 12 10:59:04 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FriendList(object):
    def setupUi(self, FriendList):
        FriendList.setObjectName("FriendList")
        FriendList.resize(353, 493)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/quip/Images/quip-bubble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FriendList.setWindowIcon(icon)
        FriendList.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(FriendList)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 0, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.profileWidget = QtGui.QWidget(self.centralwidget)
        self.profileWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.profileWidget.setStyleSheet("background-color: white;")
        self.profileWidget.setObjectName("profileWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.profileWidget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.avatarLabel = QtGui.QLabel(self.profileWidget)
        self.avatarLabel.setAutoFillBackground(False)
        self.avatarLabel.setStyleSheet("border-width: 3px;\n"
"border-style: groove;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 255);")
        self.avatarLabel.setText("")
        self.avatarLabel.setPixmap(QtGui.QPixmap(":/quip/Images/default-avatar-64x64.png"))
        self.avatarLabel.setObjectName("avatarLabel")
        self.horizontalLayout_2.addWidget(self.avatarLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.profileVBoxLayout = QtGui.QVBoxLayout()
        self.profileVBoxLayout.setSpacing(0)
        self.profileVBoxLayout.setContentsMargins(-1, 0, -1, -1)
        self.profileVBoxLayout.setObjectName("profileVBoxLayout")
        self.aliasLineEdit = QtGui.QLineEdit(self.profileWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.aliasLineEdit.setFont(font)
        self.aliasLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aliasLineEdit.setStyleSheet("")
        self.aliasLineEdit.setText("")
        self.aliasLineEdit.setMaxLength(16)
        self.aliasLineEdit.setFrame(False)
        self.aliasLineEdit.setObjectName("aliasLineEdit")
        self.profileVBoxLayout.addWidget(self.aliasLineEdit)
        self.commentTextEdit = QtGui.QTextEdit(self.profileWidget)
        self.commentTextEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.commentTextEdit.setObjectName("commentTextEdit")
        self.profileVBoxLayout.addWidget(self.commentTextEdit)
        self.horizontalLayout.addLayout(self.profileVBoxLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.profileWidget)
        self.friendsListView = QtGui.QListView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.friendsListView.sizePolicy().hasHeightForWidth())
        self.friendsListView.setSizePolicy(sizePolicy)
        self.friendsListView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.friendsListView.setFrameShadow(QtGui.QFrame.Sunken)
        self.friendsListView.setIconSize(QtCore.QSize(32, 32))
        self.friendsListView.setObjectName("friendsListView")
        self.verticalLayout.addWidget(self.friendsListView)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        FriendList.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FriendList)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 27))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFriends = QtGui.QMenu(self.menubar)
        self.menuFriends.setObjectName("menuFriends")
        self.menuStatus = QtGui.QMenu(self.menubar)
        self.menuStatus.setObjectName("menuStatus")
        FriendList.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(FriendList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.BottomToolBarArea)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        FriendList.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar)
        self.actionSearchProfiles = QtGui.QAction(FriendList)
        self.actionSearchProfiles.setObjectName("actionSearchProfiles")
        self.actionQuit = QtGui.QAction(FriendList)
        self.actionQuit.setObjectName("actionQuit")
        self.actionFriendAdd = QtGui.QAction(FriendList)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/quip/Images/add-user-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFriendAdd.setIcon(icon1)
        self.actionFriendAdd.setObjectName("actionFriendAdd")
        self.actionSettings = QtGui.QAction(FriendList)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/quip/Images/settings-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon2)
        self.actionSettings.setObjectName("actionSettings")
        self.actionOnline = QtGui.QAction(FriendList)
        self.actionOnline.setObjectName("actionOnline")
        self.actionAway = QtGui.QAction(FriendList)
        self.actionAway.setObjectName("actionAway")
        self.actionBusy = QtGui.QAction(FriendList)
        self.actionBusy.setObjectName("actionBusy")
        self.actionInvisible = QtGui.QAction(FriendList)
        self.actionInvisible.setObjectName("actionInvisible")
        self.actionDeleteFriend = QtGui.QAction(FriendList)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/quip/Images/dialog-error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteFriend.setIcon(icon3)
        self.actionDeleteFriend.setObjectName("actionDeleteFriend")
        self.actionTransfers = QtGui.QAction(FriendList)
        self.actionTransfers.setObjectName("actionTransfers")
        self.actionPatron = QtGui.QAction(FriendList)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/quip/Images/notpatron.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPatron.setIcon(icon4)
        self.actionPatron.setObjectName("actionPatron")
        self.menuFile.addAction(self.actionTransfers)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFriends.addAction(self.actionSearchProfiles)
        self.menuFriends.addSeparator()
        self.menuStatus.addAction(self.actionOnline)
        self.menuStatus.addAction(self.actionAway)
        self.menuStatus.addAction(self.actionBusy)
        self.menuStatus.addAction(self.actionInvisible)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFriends.menuAction())
        self.menubar.addAction(self.menuStatus.menuAction())
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addAction(self.actionPatron)
        self.toolBar.addAction(self.actionFriendAdd)

        self.retranslateUi(FriendList)
        QtCore.QMetaObject.connectSlotsByName(FriendList)

    def retranslateUi(self, FriendList):
        FriendList.setWindowTitle(QtGui.QApplication.translate("FriendList", "Quip", None, QtGui.QApplication.UnicodeUTF8))
        self.commentTextEdit.setHtml(QtGui.QApplication.translate("FriendList", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("FriendList", "Quip", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFriends.setTitle(QtGui.QApplication.translate("FriendList", "Friends", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStatus.setTitle(QtGui.QApplication.translate("FriendList", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("FriendList", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearchProfiles.setText(QtGui.QApplication.translate("FriendList", "Search Profiles", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSearchProfiles.setShortcut(QtGui.QApplication.translate("FriendList", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("FriendList", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("FriendList", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFriendAdd.setText(QtGui.QApplication.translate("FriendList", "Add Contact", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFriendAdd.setIconText(QtGui.QApplication.translate("FriendList", "Add Contact", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFriendAdd.setToolTip(QtGui.QApplication.translate("FriendList", "Add Contact", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("FriendList", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setToolTip(QtGui.QApplication.translate("FriendList", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setShortcut(QtGui.QApplication.translate("FriendList", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOnline.setText(QtGui.QApplication.translate("FriendList", "Online", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOnline.setShortcut(QtGui.QApplication.translate("FriendList", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAway.setText(QtGui.QApplication.translate("FriendList", "Away", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAway.setShortcut(QtGui.QApplication.translate("FriendList", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBusy.setText(QtGui.QApplication.translate("FriendList", "Busy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBusy.setShortcut(QtGui.QApplication.translate("FriendList", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvisible.setText(QtGui.QApplication.translate("FriendList", "Invisible", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvisible.setShortcut(QtGui.QApplication.translate("FriendList", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteFriend.setText(QtGui.QApplication.translate("FriendList", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTransfers.setText(QtGui.QApplication.translate("FriendList", "File Transfers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTransfers.setShortcut(QtGui.QApplication.translate("FriendList", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPatron.setText(QtGui.QApplication.translate("FriendList", "Patronage", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPatron.setIconText(QtGui.QApplication.translate("FriendList", "Patronage", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPatron.setToolTip(QtGui.QApplication.translate("FriendList", "Patronage", None, QtGui.QApplication.UnicodeUTF8))

from . import quip_qt_rc
from . import quip_qt_rc
