# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newAccount.ui'
#
# Created: Thu Feb 12 10:59:04 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NewAccount(object):
    def setupUi(self, NewAccount):
        NewAccount.setObjectName("NewAccount")
        NewAccount.resize(702, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/quip/Images/quip-bubble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewAccount.setWindowIcon(icon)
        NewAccount.setStyleSheet("background-color: white;")
        self.centralwidget = QtGui.QWidget(NewAccount)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtGui.QFormLayout(self.centralwidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.aliasLabel = QtGui.QLabel(self.centralwidget)
        self.aliasLabel.setObjectName("aliasLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.aliasLabel)
        self.aliasLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.aliasLineEdit.setMaxLength(16)
        self.aliasLineEdit.setObjectName("aliasLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.aliasLineEdit)
        self.firstnameLabel = QtGui.QLabel(self.centralwidget)
        self.firstnameLabel.setObjectName("firstnameLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.firstnameLabel)
        self.firstnameLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.firstnameLineEdit.setMaxLength(16)
        self.firstnameLineEdit.setObjectName("firstnameLineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.firstnameLineEdit)
        self.lastnameLabel = QtGui.QLabel(self.centralwidget)
        self.lastnameLabel.setObjectName("lastnameLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lastnameLabel)
        self.lastnameLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lastnameLineEdit.setMaxLength(32)
        self.lastnameLineEdit.setObjectName("lastnameLineEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lastnameLineEdit)
        self.countryLabel = QtGui.QLabel(self.centralwidget)
        self.countryLabel.setObjectName("countryLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.countryLabel)
        self.countryLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.countryLineEdit.setMaxLength(64)
        self.countryLineEdit.setObjectName("countryLineEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.countryLineEdit)
        self.stateLabel = QtGui.QLabel(self.centralwidget)
        self.stateLabel.setObjectName("stateLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.stateLabel)
        self.stateLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.stateLineEdit.setMaxLength(64)
        self.stateLineEdit.setObjectName("stateLineEdit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.stateLineEdit)
        self.cityLabel = QtGui.QLabel(self.centralwidget)
        self.cityLabel.setObjectName("cityLabel")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.cityLabel)
        self.cityLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.cityLineEdit.setMaxLength(64)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.cityLineEdit)
        self.commentLabel = QtGui.QLabel(self.centralwidget)
        self.commentLabel.setObjectName("commentLabel")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.commentLabel)
        self.commentLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.commentLineEdit.setMaxLength(128)
        self.commentLineEdit.setObjectName("commentLineEdit")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.commentLineEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(200, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.createAccountFailedLabel = QtGui.QLabel(self.centralwidget)
        self.createAccountFailedLabel.setStyleSheet("color: red;")
        self.createAccountFailedLabel.setObjectName("createAccountFailedLabel")
        self.horizontalLayout.addWidget(self.createAccountFailedLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.createAccountButton = QtGui.QToolButton(self.centralwidget)
        self.createAccountButton.setStyleSheet("background-color: rgba(140, 217, 140, 100);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/quip/Images/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createAccountButton.setIcon(icon1)
        self.createAccountButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.createAccountButton.setObjectName("createAccountButton")
        self.horizontalLayout.addWidget(self.createAccountButton)
        self.formLayout.setLayout(12, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.infoTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.infoTextEdit.setStyleSheet("border-top: 1px dotted black;")
        self.infoTextEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.infoTextEdit.setReadOnly(True)
        self.infoTextEdit.setObjectName("infoTextEdit")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.infoTextEdit)
        self.passphraseLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.passphraseLineEdit.setText("")
        self.passphraseLineEdit.setMaxLength(32)
        self.passphraseLineEdit.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.passphraseLineEdit.setObjectName("passphraseLineEdit")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.passphraseLineEdit)
        self.passphraseLabel = QtGui.QLabel(self.centralwidget)
        self.passphraseLabel.setObjectName("passphraseLabel")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.passphraseLabel)
        self.emailLabel = QtGui.QLabel(self.centralwidget)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.emailLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.emailLineEdit.setMaxLength(255)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.emailLineEdit)
        NewAccount.setCentralWidget(self.centralwidget)

        self.retranslateUi(NewAccount)
        QtCore.QMetaObject.connectSlotsByName(NewAccount)

    def retranslateUi(self, NewAccount):
        NewAccount.setWindowTitle(QtGui.QApplication.translate("NewAccount", "New Account", None, QtGui.QApplication.UnicodeUTF8))
        self.aliasLabel.setText(QtGui.QApplication.translate("NewAccount", "Alias", None, QtGui.QApplication.UnicodeUTF8))
        self.aliasLineEdit.setPlaceholderText(QtGui.QApplication.translate("NewAccount", "Alias/Nickname for this account", None, QtGui.QApplication.UnicodeUTF8))
        self.firstnameLabel.setText(QtGui.QApplication.translate("NewAccount", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.firstnameLineEdit.setPlaceholderText(QtGui.QApplication.translate("NewAccount", "First name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastnameLabel.setText(QtGui.QApplication.translate("NewAccount", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastnameLineEdit.setPlaceholderText(QtGui.QApplication.translate("NewAccount", "Last name", None, QtGui.QApplication.UnicodeUTF8))
        self.countryLabel.setText(QtGui.QApplication.translate("NewAccount", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.countryLineEdit.setPlaceholderText(QtGui.QApplication.translate("NewAccount", "Country of residence", None, QtGui.QApplication.UnicodeUTF8))
        self.stateLabel.setText(QtGui.QApplication.translate("NewAccount", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.stateLineEdit.setPlaceholderText(QtGui.QApplication.translate("NewAccount", "State/Territory/Province/Protectorate", None, QtGui.QApplication.UnicodeUTF8))
        self.cityLabel.setText(QtGui.QApplication.translate("NewAccount", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.cityLineEdit.setPlaceholderText(QtGui.QApplication.translate("NewAccount", "City/Town/Village", None, QtGui.QApplication.UnicodeUTF8))
        self.commentLabel.setText(QtGui.QApplication.translate("NewAccount", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.commentLineEdit.setPlaceholderText(QtGui.QApplication.translate("NewAccount", "Status message to be displayed", None, QtGui.QApplication.UnicodeUTF8))
        self.createAccountFailedLabel.setText(QtGui.QApplication.translate("NewAccount", "Unable to create account. Try again soon.", None, QtGui.QApplication.UnicodeUTF8))
        self.createAccountButton.setText(QtGui.QApplication.translate("NewAccount", "Create Account", None, QtGui.QApplication.UnicodeUTF8))
        self.infoTextEdit.setHtml(QtGui.QApplication.translate("NewAccount", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">All the profile fields above are <span style=\" font-weight:600;\">optional</span>. Adding profile information will allow people to search for your profile, the more profile information you provide - the easier it is for people to locate your profile.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.passphraseLineEdit.setPlaceholderText(QtGui.QApplication.translate("NewAccount", "Account passphrase (required). Minimum 8 characters, maximum 32", None, QtGui.QApplication.UnicodeUTF8))
        self.passphraseLabel.setText(QtGui.QApplication.translate("NewAccount", "Passphrase", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLabel.setText(QtGui.QApplication.translate("NewAccount", "E-mail", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLineEdit.setPlaceholderText(QtGui.QApplication.translate("NewAccount", "Address for account recovery and notifications (Not viewable by users)", None, QtGui.QApplication.UnicodeUTF8))

from . import quip_qt_rc
