# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profileSearch.ui'
#
# Created: Tue Dec 16 15:46:23 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ProfileSearch(object):
    def setupUi(self, ProfileSearch):
        ProfileSearch.setObjectName("ProfileSearch")
        ProfileSearch.resize(699, 472)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/quip/Images/quip-bubble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ProfileSearch.setWindowIcon(icon)
        ProfileSearch.setStyleSheet("background-color: white;")
        self.centralwidget = QtGui.QWidget(ProfileSearch)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.searchLabel.setFont(font)
        self.searchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.searchLabel.setObjectName("searchLabel")
        self.verticalLayout.addWidget(self.searchLabel)
        self.titleSpaceWidget = QtGui.QWidget(self.centralwidget)
        self.titleSpaceWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.titleSpaceWidget.setObjectName("titleSpaceWidget")
        self.verticalLayout.addWidget(self.titleSpaceWidget)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.useridLabel = QtGui.QLabel(self.centralwidget)
        self.useridLabel.setObjectName("useridLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.useridLabel)
        self.useridLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.useridLineEdit.setMaxLength(36)
        self.useridLineEdit.setObjectName("useridLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.useridLineEdit)
        self.searchDetailsPlainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchDetailsPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.searchDetailsPlainTextEdit.setSizePolicy(sizePolicy)
        self.searchDetailsPlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.searchDetailsPlainTextEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.searchDetailsPlainTextEdit.setAcceptDrops(False)
        self.searchDetailsPlainTextEdit.setStyleSheet("border-top: 1px dotted black;")
        self.searchDetailsPlainTextEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.searchDetailsPlainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.searchDetailsPlainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.searchDetailsPlainTextEdit.setReadOnly(True)
        self.searchDetailsPlainTextEdit.setObjectName("searchDetailsPlainTextEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.searchDetailsPlainTextEdit)
        self.aliasLabel = QtGui.QLabel(self.centralwidget)
        self.aliasLabel.setObjectName("aliasLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.aliasLabel)
        self.aliasLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.aliasLineEdit.setMaxLength(16)
        self.aliasLineEdit.setObjectName("aliasLineEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.aliasLineEdit)
        self.firstnameLabel = QtGui.QLabel(self.centralwidget)
        self.firstnameLabel.setObjectName("firstnameLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.firstnameLabel)
        self.firstnameLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.firstnameLineEdit.setMaxLength(16)
        self.firstnameLineEdit.setObjectName("firstnameLineEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.firstnameLineEdit)
        self.lastnameLabel = QtGui.QLabel(self.centralwidget)
        self.lastnameLabel.setObjectName("lastnameLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lastnameLabel)
        self.lastnameLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lastnameLineEdit.setMaxLength(32)
        self.lastnameLineEdit.setObjectName("lastnameLineEdit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lastnameLineEdit)
        self.countryLabel = QtGui.QLabel(self.centralwidget)
        self.countryLabel.setObjectName("countryLabel")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.countryLabel)
        self.countryLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.countryLineEdit.setMaxLength(64)
        self.countryLineEdit.setObjectName("countryLineEdit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.countryLineEdit)
        self.stateLabel = QtGui.QLabel(self.centralwidget)
        self.stateLabel.setObjectName("stateLabel")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.stateLabel)
        self.stateLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.stateLineEdit.setMaxLength(64)
        self.stateLineEdit.setObjectName("stateLineEdit")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.stateLineEdit)
        self.cityLabel = QtGui.QLabel(self.centralwidget)
        self.cityLabel.setObjectName("cityLabel")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.cityLabel)
        self.cityLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.cityLineEdit.setMaxLength(64)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.cityLineEdit)
        self.commentLabel = QtGui.QLabel(self.centralwidget)
        self.commentLabel.setObjectName("commentLabel")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.commentLabel)
        self.commentLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.commentLineEdit.setMaxLength(128)
        self.commentLineEdit.setObjectName("commentLineEdit")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.commentLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.searchHBoxLayout = QtGui.QHBoxLayout()
        self.searchHBoxLayout.setObjectName("searchHBoxLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.searchHBoxLayout.addItem(spacerItem)
        self.searchProfilesButton = QtGui.QToolButton(self.centralwidget)
        self.searchProfilesButton.setStyleSheet("background-color: rgba(140, 217, 140, 100);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/quip/Images/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchProfilesButton.setIcon(icon1)
        self.searchProfilesButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.searchProfilesButton.setObjectName("searchProfilesButton")
        self.searchHBoxLayout.addWidget(self.searchProfilesButton)
        self.verticalLayout.addLayout(self.searchHBoxLayout)
        ProfileSearch.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProfileSearch)
        QtCore.QMetaObject.connectSlotsByName(ProfileSearch)

    def retranslateUi(self, ProfileSearch):
        ProfileSearch.setWindowTitle(QtGui.QApplication.translate("ProfileSearch", "Contact Search", None, QtGui.QApplication.UnicodeUTF8))
        self.searchLabel.setText(QtGui.QApplication.translate("ProfileSearch", "Search for contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.useridLabel.setText(QtGui.QApplication.translate("ProfileSearch", "User ID", None, QtGui.QApplication.UnicodeUTF8))
        self.useridLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileSearch", "Unique User ID (36 characters)", None, QtGui.QApplication.UnicodeUTF8))
        self.searchDetailsPlainTextEdit.setPlainText(QtGui.QApplication.translate("ProfileSearch", "\n"
"OR search profiles using any (or all) of the fields below", None, QtGui.QApplication.UnicodeUTF8))
        self.aliasLabel.setText(QtGui.QApplication.translate("ProfileSearch", "Alias", None, QtGui.QApplication.UnicodeUTF8))
        self.aliasLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileSearch", "Alias/Nickname", None, QtGui.QApplication.UnicodeUTF8))
        self.firstnameLabel.setText(QtGui.QApplication.translate("ProfileSearch", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.firstnameLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileSearch", "First name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastnameLabel.setText(QtGui.QApplication.translate("ProfileSearch", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastnameLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileSearch", "Last name", None, QtGui.QApplication.UnicodeUTF8))
        self.countryLabel.setText(QtGui.QApplication.translate("ProfileSearch", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.countryLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileSearch", "Country of residence", None, QtGui.QApplication.UnicodeUTF8))
        self.stateLabel.setText(QtGui.QApplication.translate("ProfileSearch", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.stateLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileSearch", "State/Territory/Province/Protectorate", None, QtGui.QApplication.UnicodeUTF8))
        self.cityLabel.setText(QtGui.QApplication.translate("ProfileSearch", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.cityLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileSearch", "City/Town/Village", None, QtGui.QApplication.UnicodeUTF8))
        self.commentLabel.setText(QtGui.QApplication.translate("ProfileSearch", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.commentLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileSearch", "Status message displayed by contact", None, QtGui.QApplication.UnicodeUTF8))
        self.searchProfilesButton.setText(QtGui.QApplication.translate("ProfileSearch", "Search", None, QtGui.QApplication.UnicodeUTF8))

from . import quip_qt_rc
