# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profileView.ui'
#
# Created: Thu Feb 12 10:59:05 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ProfileView(object):
    def setupUi(self, ProfileView):
        ProfileView.setObjectName("ProfileView")
        ProfileView.resize(646, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/quip/Images/quip-bubble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ProfileView.setWindowIcon(icon)
        ProfileView.setStyleSheet("background-color: white;")
        self.centralwidget = QtGui.QWidget(ProfileView)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.avatarLabel = QtGui.QLabel(self.centralwidget)
        self.avatarLabel.setAutoFillBackground(False)
        self.avatarLabel.setStyleSheet("border-width: 3px;\n"
"border-style: groove;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 255);")
        self.avatarLabel.setText("")
        self.avatarLabel.setPixmap(QtGui.QPixmap(":/quip/Images/default-avatar-64x64.png"))
        self.avatarLabel.setObjectName("avatarLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.avatarLabel)
        self.addAvatarButton = QtGui.QPushButton(self.centralwidget)
        self.addAvatarButton.setMinimumSize(QtCore.QSize(32, 32))
        self.addAvatarButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.addAvatarButton.setStyleSheet("border: none;")
        self.addAvatarButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/quip/Images/insert-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addAvatarButton.setIcon(icon1)
        self.addAvatarButton.setIconSize(QtCore.QSize(28, 28))
        self.addAvatarButton.setFlat(True)
        self.addAvatarButton.setObjectName("addAvatarButton")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.addAvatarButton)
        self.spacerWidget = QtGui.QWidget(self.centralwidget)
        self.spacerWidget.setObjectName("spacerWidget")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.spacerWidget)
        self.useridLabel = QtGui.QLabel(self.centralwidget)
        self.useridLabel.setObjectName("useridLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.useridLabel)
        self.useridLabelText = QtGui.QLabel(self.centralwidget)
        self.useridLabelText.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.useridLabelText.setObjectName("useridLabelText")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.useridLabelText)
        self.aliasLabel = QtGui.QLabel(self.centralwidget)
        self.aliasLabel.setObjectName("aliasLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.aliasLabel)
        self.aliasLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.aliasLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.aliasLineEdit.setMaxLength(16)
        self.aliasLineEdit.setReadOnly(True)
        self.aliasLineEdit.setObjectName("aliasLineEdit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.aliasLineEdit)
        self.firstnameLabel = QtGui.QLabel(self.centralwidget)
        self.firstnameLabel.setObjectName("firstnameLabel")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.firstnameLabel)
        self.firstnameLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.firstnameLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.firstnameLineEdit.setMaxLength(16)
        self.firstnameLineEdit.setReadOnly(True)
        self.firstnameLineEdit.setObjectName("firstnameLineEdit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.firstnameLineEdit)
        self.lastnameLabel = QtGui.QLabel(self.centralwidget)
        self.lastnameLabel.setObjectName("lastnameLabel")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lastnameLabel)
        self.lastnameLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lastnameLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lastnameLineEdit.setMaxLength(32)
        self.lastnameLineEdit.setReadOnly(True)
        self.lastnameLineEdit.setObjectName("lastnameLineEdit")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lastnameLineEdit)
        self.countryLabel = QtGui.QLabel(self.centralwidget)
        self.countryLabel.setObjectName("countryLabel")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.countryLabel)
        self.countryLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.countryLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.countryLineEdit.setMaxLength(64)
        self.countryLineEdit.setReadOnly(True)
        self.countryLineEdit.setObjectName("countryLineEdit")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.countryLineEdit)
        self.stateLabel = QtGui.QLabel(self.centralwidget)
        self.stateLabel.setObjectName("stateLabel")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.stateLabel)
        self.stateLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.stateLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stateLineEdit.setMaxLength(64)
        self.stateLineEdit.setReadOnly(True)
        self.stateLineEdit.setObjectName("stateLineEdit")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.stateLineEdit)
        self.cityLabel = QtGui.QLabel(self.centralwidget)
        self.cityLabel.setObjectName("cityLabel")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.cityLabel)
        self.cityLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.cityLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cityLineEdit.setMaxLength(64)
        self.cityLineEdit.setReadOnly(True)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.cityLineEdit)
        self.commentLabel = QtGui.QLabel(self.centralwidget)
        self.commentLabel.setObjectName("commentLabel")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.commentLabel)
        self.commentLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.commentLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.commentLineEdit.setText("")
        self.commentLineEdit.setMaxLength(128)
        self.commentLineEdit.setReadOnly(True)
        self.commentLineEdit.setObjectName("commentLineEdit")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.commentLineEdit)
        self.emailLabel = QtGui.QLabel(self.centralwidget)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.emailLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.emailLineEdit.setMaxLength(255)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.emailLineEdit)
        self.profileHBoxLayout = QtGui.QHBoxLayout()
        self.profileHBoxLayout.setObjectName("profileHBoxLayout")
        self.profileLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileLabel.sizePolicy().hasHeightForWidth())
        self.profileLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.profileLabel.setFont(font)
        self.profileLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profileLabel.setObjectName("profileLabel")
        self.profileHBoxLayout.addWidget(self.profileLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.profileHBoxLayout.addItem(spacerItem)
        self.patronVBoxLayout = QtGui.QVBoxLayout()
        self.patronVBoxLayout.setObjectName("patronVBoxLayout")
        self.patronButton = QtGui.QPushButton(self.centralwidget)
        self.patronButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.patronButton.setStyleSheet("border:none;")
        self.patronButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/quip/Images/notpatron.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patronButton.setIcon(icon2)
        self.patronButton.setIconSize(QtCore.QSize(32, 32))
        self.patronButton.setFlat(True)
        self.patronButton.setObjectName("patronButton")
        self.patronVBoxLayout.addWidget(self.patronButton)
        self.patronTimeLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.patronTimeLabel.setFont(font)
        self.patronTimeLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        self.patronTimeLabel.setObjectName("patronTimeLabel")
        self.patronVBoxLayout.addWidget(self.patronTimeLabel)
        self.profileHBoxLayout.addLayout(self.patronVBoxLayout)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.profileHBoxLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.saveHBoxLayout = QtGui.QHBoxLayout()
        self.saveHBoxLayout.setObjectName("saveHBoxLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.saveHBoxLayout.addItem(spacerItem1)
        self.saveButton = QtGui.QToolButton(self.centralwidget)
        self.saveButton.setStyleSheet("background-color: rgba(140, 217, 140, 100);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/quip/Images/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon3)
        self.saveButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.saveButton.setObjectName("saveButton")
        self.saveHBoxLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.saveHBoxLayout)
        ProfileView.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProfileView)
        QtCore.QMetaObject.connectSlotsByName(ProfileView)

    def retranslateUi(self, ProfileView):
        ProfileView.setWindowTitle(QtGui.QApplication.translate("ProfileView", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.useridLabel.setText(QtGui.QApplication.translate("ProfileView", "User ID", None, QtGui.QApplication.UnicodeUTF8))
        self.useridLabelText.setText(QtGui.QApplication.translate("ProfileView", "User ID", None, QtGui.QApplication.UnicodeUTF8))
        self.aliasLabel.setText(QtGui.QApplication.translate("ProfileView", "Alias", None, QtGui.QApplication.UnicodeUTF8))
        self.aliasLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileView", "Alias/Nickname", None, QtGui.QApplication.UnicodeUTF8))
        self.firstnameLabel.setText(QtGui.QApplication.translate("ProfileView", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.firstnameLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileView", "First name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastnameLabel.setText(QtGui.QApplication.translate("ProfileView", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastnameLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileView", "Last name", None, QtGui.QApplication.UnicodeUTF8))
        self.countryLabel.setText(QtGui.QApplication.translate("ProfileView", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.countryLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileView", "Country of residence", None, QtGui.QApplication.UnicodeUTF8))
        self.stateLabel.setText(QtGui.QApplication.translate("ProfileView", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.stateLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileView", "State/Territory/Province/Protectorate", None, QtGui.QApplication.UnicodeUTF8))
        self.cityLabel.setText(QtGui.QApplication.translate("ProfileView", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.cityLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileView", "City/Town/Village", None, QtGui.QApplication.UnicodeUTF8))
        self.commentLabel.setText(QtGui.QApplication.translate("ProfileView", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.commentLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileView", "Status message displayed by contact", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLabel.setText(QtGui.QApplication.translate("ProfileView", "E-mail", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLineEdit.setPlaceholderText(QtGui.QApplication.translate("ProfileView", "Address for account recovery and notifications (Not viewable by users)", None, QtGui.QApplication.UnicodeUTF8))
        self.profileLabel.setText(QtGui.QApplication.translate("ProfileView", "Specified User\'s Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.patronTimeLabel.setText(QtGui.QApplication.translate("ProfileView", "03:41PM 11th Feb 15 UTC", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("ProfileView", "Save", None, QtGui.QApplication.UnicodeUTF8))

from . import quip_qt_rc
