# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchResults.ui'
#
# Created: Tue Dec 16 15:46:23 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SearchResults(object):
    def setupUi(self, SearchResults):
        SearchResults.setObjectName("SearchResults")
        SearchResults.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/quip/Images/quip-bubble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearchResults.setWindowIcon(icon)
        SearchResults.setStyleSheet("background-color: white;")
        self.centralwidget = QtGui.QWidget(SearchResults)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerHBoxLayout = QtGui.QHBoxLayout()
        self.headerHBoxLayout.setObjectName("headerHBoxLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.headerHBoxLayout.addItem(spacerItem)
        self.searchLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.searchLabel.setFont(font)
        self.searchLabel.setObjectName("searchLabel")
        self.headerHBoxLayout.addWidget(self.searchLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.headerHBoxLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.headerHBoxLayout)
        self.sortHBoxLayout = QtGui.QHBoxLayout()
        self.sortHBoxLayout.setObjectName("sortHBoxLayout")
        self.sortLabel = QtGui.QLabel(self.centralwidget)
        self.sortLabel.setObjectName("sortLabel")
        self.sortHBoxLayout.addWidget(self.sortLabel)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setStyleSheet("background-color: rgb(236, 236, 236);")
        self.comboBox.setObjectName("comboBox")
        self.sortHBoxLayout.addWidget(self.comboBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.sortHBoxLayout.addItem(spacerItem2)
        self.countLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.countLabel.setFont(font)
        self.countLabel.setObjectName("countLabel")
        self.sortHBoxLayout.addWidget(self.countLabel)
        self.verticalLayout.addLayout(self.sortHBoxLayout)
        self.profilesListView = QtGui.QListView(self.centralwidget)
        self.profilesListView.setStyleSheet("border-width: 1px;\n"
"border-radius: 5px;\n"
"border-style: dashed;\n"
"border-color: rgba(213, 213, 213, 150);\n"
"background-color: rgb(240, 240, 240);")
        self.profilesListView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.profilesListView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.profilesListView.setAlternatingRowColors(True)
        self.profilesListView.setObjectName("profilesListView")
        self.verticalLayout.addWidget(self.profilesListView)
        self.messageLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.messageLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.messageLineEdit.setMaxLength(110)
        self.messageLineEdit.setObjectName("messageLineEdit")
        self.verticalLayout.addWidget(self.messageLineEdit)
        self.commandHBoxLayout = QtGui.QHBoxLayout()
        self.commandHBoxLayout.setObjectName("commandHBoxLayout")
        self.previousButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousButton.sizePolicy().hasHeightForWidth())
        self.previousButton.setSizePolicy(sizePolicy)
        self.previousButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.previousButton.setStyleSheet("border-style: none;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/quip/Images/send-left-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon1)
        self.previousButton.setFlat(True)
        self.previousButton.setObjectName("previousButton")
        self.commandHBoxLayout.addWidget(self.previousButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.commandHBoxLayout.addItem(spacerItem3)
        self.moreButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moreButton.sizePolicy().hasHeightForWidth())
        self.moreButton.setSizePolicy(sizePolicy)
        self.moreButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.moreButton.setStyleSheet("border-style: dotted;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/quip/Images/recurring-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moreButton.setIcon(icon2)
        self.moreButton.setFlat(True)
        self.moreButton.setObjectName("moreButton")
        self.commandHBoxLayout.addWidget(self.moreButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.commandHBoxLayout.addItem(spacerItem4)
        self.addContactButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addContactButton.sizePolicy().hasHeightForWidth())
        self.addContactButton.setSizePolicy(sizePolicy)
        self.addContactButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.addContactButton.setStyleSheet("border-style: none;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/quip/Images/add-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addContactButton.setIcon(icon3)
        self.addContactButton.setIconSize(QtCore.QSize(32, 32))
        self.addContactButton.setFlat(True)
        self.addContactButton.setObjectName("addContactButton")
        self.commandHBoxLayout.addWidget(self.addContactButton)
        self.verticalLayout.addLayout(self.commandHBoxLayout)
        SearchResults.setCentralWidget(self.centralwidget)

        self.retranslateUi(SearchResults)
        QtCore.QMetaObject.connectSlotsByName(SearchResults)

    def retranslateUi(self, SearchResults):
        SearchResults.setWindowTitle(QtGui.QApplication.translate("SearchResults", "Search Results", None, QtGui.QApplication.UnicodeUTF8))
        self.searchLabel.setText(QtGui.QApplication.translate("SearchResults", "Search Results", None, QtGui.QApplication.UnicodeUTF8))
        self.sortLabel.setText(QtGui.QApplication.translate("SearchResults", "Sort By", None, QtGui.QApplication.UnicodeUTF8))
        self.countLabel.setText(QtGui.QApplication.translate("SearchResults", "0 to 100", None, QtGui.QApplication.UnicodeUTF8))
        self.messageLineEdit.setPlaceholderText(QtGui.QApplication.translate("SearchResults", "Any message typed here will be sent with the friend requests", None, QtGui.QApplication.UnicodeUTF8))
        self.previousButton.setText(QtGui.QApplication.translate("SearchResults", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.moreButton.setText(QtGui.QApplication.translate("SearchResults", "More", None, QtGui.QApplication.UnicodeUTF8))
        self.addContactButton.setText(QtGui.QApplication.translate("SearchResults", "Add Contacts", None, QtGui.QApplication.UnicodeUTF8))

from . import quip_qt_rc
