# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Tue Dec 16 15:46:23 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/quip/Images/quip-bubble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setStyleSheet("background-color: white;")
        self.centralwidget = QtGui.QWidget(Settings)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.networkPage = QtGui.QWidget()
        self.networkPage.setObjectName("networkPage")
        self.verticalLayout = QtGui.QVBoxLayout(self.networkPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.networkFormLayout = QtGui.QFormLayout()
        self.networkFormLayout.setObjectName("networkFormLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.networkFormLayout.setItem(0, QtGui.QFormLayout.LabelRole, spacerItem)
        self.ipAddressLabel = QtGui.QLabel(self.networkPage)
        self.ipAddressLabel.setObjectName("ipAddressLabel")
        self.networkFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ipAddressLabel)
        self.ipAdressLineEdit = QtGui.QLineEdit(self.networkPage)
        self.ipAdressLineEdit.setObjectName("ipAdressLineEdit")
        self.networkFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ipAdressLineEdit)
        self.portLabel = QtGui.QLabel(self.networkPage)
        self.portLabel.setObjectName("portLabel")
        self.networkFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.portLabel)
        self.portHBoxLayout = QtGui.QHBoxLayout()
        self.portHBoxLayout.setObjectName("portHBoxLayout")
        self.portLineEdit = QtGui.QLineEdit(self.networkPage)
        self.portLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.portLineEdit.setObjectName("portLineEdit")
        self.portHBoxLayout.addWidget(self.portLineEdit)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.portHBoxLayout.addItem(spacerItem1)
        self.portRandomiseButton = QtGui.QPushButton(self.networkPage)
        self.portRandomiseButton.setFocusPolicy(QtCore.Qt.TabFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/quip/Images/die-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.portRandomiseButton.setIcon(icon1)
        self.portRandomiseButton.setFlat(True)
        self.portRandomiseButton.setObjectName("portRandomiseButton")
        self.portHBoxLayout.addWidget(self.portRandomiseButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.portHBoxLayout.addItem(spacerItem2)
        self.networkFormLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.portHBoxLayout)
        self.verticalLayout.addLayout(self.networkFormLayout)
        self.timeoutFormLayout = QtGui.QFormLayout()
        self.timeoutFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.timeoutFormLayout.setObjectName("timeoutFormLayout")
        self.protocolTimeoutLabel = QtGui.QLabel(self.networkPage)
        self.protocolTimeoutLabel.setObjectName("protocolTimeoutLabel")
        self.timeoutFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.protocolTimeoutLabel)
        self.protocolTimeoutLineEdit = QtGui.QLineEdit(self.networkPage)
        self.protocolTimeoutLineEdit.setObjectName("protocolTimeoutLineEdit")
        self.timeoutFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.protocolTimeoutLineEdit)
        self.fileTransferLabel = QtGui.QLabel(self.networkPage)
        self.fileTransferLabel.setObjectName("fileTransferLabel")
        self.timeoutFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.fileTransferLabel)
        self.fileTransferLineEdit = QtGui.QLineEdit(self.networkPage)
        self.fileTransferLineEdit.setObjectName("fileTransferLineEdit")
        self.timeoutFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.fileTransferLineEdit)
        self.chunkSizeLabel = QtGui.QLabel(self.networkPage)
        self.chunkSizeLabel.setObjectName("chunkSizeLabel")
        self.timeoutFormLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.chunkSizeLabel)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.timeoutFormLayout.setItem(2, QtGui.QFormLayout.LabelRole, spacerItem3)
        self.chunkSizeLineEdit = QtGui.QLineEdit(self.networkPage)
        self.chunkSizeLineEdit.setObjectName("chunkSizeLineEdit")
        self.timeoutFormLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.chunkSizeLineEdit)
        self.chunkSizeDescriptionLabel = QtGui.QLabel(self.networkPage)
        self.chunkSizeDescriptionLabel.setStyleSheet("color: grey;")
        self.chunkSizeDescriptionLabel.setObjectName("chunkSizeDescriptionLabel")
        self.timeoutFormLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.chunkSizeDescriptionLabel)
        self.verticalLayout.addLayout(self.timeoutFormLayout)
        self.stackedWidget.addWidget(self.networkPage)
        self.storagePage = QtGui.QWidget()
        self.storagePage.setObjectName("storagePage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.storagePage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtGui.QFormLayout.LabelRole, spacerItem4)
        self.downloadLabel = QtGui.QLabel(self.storagePage)
        self.downloadLabel.setObjectName("downloadLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.downloadLabel)
        self.downloadHBoxLayout = QtGui.QHBoxLayout()
        self.downloadHBoxLayout.setObjectName("downloadHBoxLayout")
        self.downloadLineEdit = QtGui.QLineEdit(self.storagePage)
        self.downloadLineEdit.setEnabled(False)
        self.downloadLineEdit.setReadOnly(True)
        self.downloadLineEdit.setObjectName("downloadLineEdit")
        self.downloadHBoxLayout.addWidget(self.downloadLineEdit)
        self.downloadButton = QtGui.QPushButton(self.storagePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadButton.sizePolicy().hasHeightForWidth())
        self.downloadButton.setSizePolicy(sizePolicy)
        self.downloadButton.setFocusPolicy(QtCore.Qt.TabFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/quip/Images/folder-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadButton.setIcon(icon2)
        self.downloadButton.setFlat(True)
        self.downloadButton.setObjectName("downloadButton")
        self.downloadHBoxLayout.addWidget(self.downloadButton)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.downloadHBoxLayout)
        self.verifyHBoxLayout = QtGui.QHBoxLayout()
        self.verifyHBoxLayout.setObjectName("verifyHBoxLayout")
        self.verifyCheckbox = QtGui.QCheckBox(self.storagePage)
        self.verifyCheckbox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.verifyCheckbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verifyCheckbox.setTristate(False)
        self.verifyCheckbox.setObjectName("verifyCheckbox")
        self.verifyHBoxLayout.addWidget(self.verifyCheckbox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verifyHBoxLayout.addItem(spacerItem5)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.verifyHBoxLayout)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtGui.QFormLayout.LabelRole, spacerItem6)
        self.fileRequestLimitLabel = QtGui.QLabel(self.storagePage)
        self.fileRequestLimitLabel.setObjectName("fileRequestLimitLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.fileRequestLimitLabel)
        self.fileTransferLimitHBoxLayout = QtGui.QHBoxLayout()
        self.fileTransferLimitHBoxLayout.setObjectName("fileTransferLimitHBoxLayout")
        self.fileTransferLimitSpinBox = QtGui.QSpinBox(self.storagePage)
        self.fileTransferLimitSpinBox.setObjectName("fileTransferLimitSpinBox")
        self.fileTransferLimitHBoxLayout.addWidget(self.fileTransferLimitSpinBox)
        self.fileTransferRequestDaysLimitLabel = QtGui.QLabel(self.storagePage)
        self.fileTransferRequestDaysLimitLabel.setObjectName("fileTransferRequestDaysLimitLabel")
        self.fileTransferLimitHBoxLayout.addWidget(self.fileTransferRequestDaysLimitLabel)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.fileTransferLimitHBoxLayout.addItem(spacerItem7)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.fileTransferLimitHBoxLayout)
        self.friendRequestLimitLabel = QtGui.QLabel(self.storagePage)
        self.friendRequestLimitLabel.setObjectName("friendRequestLimitLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.friendRequestLimitLabel)
        self.friendRequestLimitHBoxLayout = QtGui.QHBoxLayout()
        self.friendRequestLimitHBoxLayout.setObjectName("friendRequestLimitHBoxLayout")
        self.friendRequestLimitSpinBox = QtGui.QSpinBox(self.storagePage)
        self.friendRequestLimitSpinBox.setObjectName("friendRequestLimitSpinBox")
        self.friendRequestLimitHBoxLayout.addWidget(self.friendRequestLimitSpinBox)
        self.friendRequestLimitDaysLabel = QtGui.QLabel(self.storagePage)
        self.friendRequestLimitDaysLabel.setObjectName("friendRequestLimitDaysLabel")
        self.friendRequestLimitHBoxLayout.addWidget(self.friendRequestLimitDaysLabel)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.friendRequestLimitHBoxLayout.addItem(spacerItem8)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.friendRequestLimitHBoxLayout)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.stackedWidget.addWidget(self.storagePage)
        self.encryptionPage = QtGui.QWidget()
        self.encryptionPage.setObjectName("encryptionPage")
        self.formLayout_2 = QtGui.QFormLayout(self.encryptionPage)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(35, 140, -1, -1)
        self.formLayout_2.setHorizontalSpacing(35)
        self.formLayout_2.setVerticalSpacing(18)
        self.formLayout_2.setObjectName("formLayout_2")
        self.storageLabel = QtGui.QLabel(self.encryptionPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.storageLabel.setFont(font)
        self.storageLabel.setObjectName("storageLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.storageLabel)
        self.encryptionDetailsLabel = QtGui.QLabel(self.encryptionPage)
        self.encryptionDetailsLabel.setObjectName("encryptionDetailsLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.encryptionDetailsLabel)
        self.keyLabel = QtGui.QLabel(self.encryptionPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.keyLabel.setFont(font)
        self.keyLabel.setObjectName("keyLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.keyLabel)
        self.keyDetailsLabel = QtGui.QLabel(self.encryptionPage)
        self.keyDetailsLabel.setObjectName("keyDetailsLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.keyDetailsLabel)
        self.signatureLabel = QtGui.QLabel(self.encryptionPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.signatureLabel.setFont(font)
        self.signatureLabel.setObjectName("signatureLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.signatureLabel)
        self.signatureDetailsLabel = QtGui.QLabel(self.encryptionPage)
        self.signatureDetailsLabel.setObjectName("signatureDetailsLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.signatureDetailsLabel)
        self.stackedWidget.addWidget(self.encryptionPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        Settings.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(Settings)
        self.toolBar.setStyleSheet("border-right: 1px dotted  gray;")
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.LeftToolBarArea)
        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        Settings.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        Settings.insertToolBarBreak(self.toolBar)
        self.actionNetwork = QtGui.QAction(Settings)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/quip/Images/settings/network.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNetwork.setIcon(icon3)
        self.actionNetwork.setObjectName("actionNetwork")
        self.actionStorage = QtGui.QAction(Settings)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/quip/Images/settings/storage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStorage.setIcon(icon4)
        self.actionStorage.setObjectName("actionStorage")
        self.actionEncryption = QtGui.QAction(Settings)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/quip/Images/settings/encryption.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEncryption.setIcon(icon5)
        self.actionEncryption.setObjectName("actionEncryption")
        self.toolBar.addAction(self.actionNetwork)
        self.toolBar.addAction(self.actionStorage)
        self.toolBar.addAction(self.actionEncryption)

        self.retranslateUi(Settings)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QtGui.QApplication.translate("Settings", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.ipAddressLabel.setText(QtGui.QApplication.translate("Settings", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.ipAdressLineEdit.setPlaceholderText(QtGui.QApplication.translate("Settings", "Leave blank to listen on all IP addresses", None, QtGui.QApplication.UnicodeUTF8))
        self.portLabel.setText(QtGui.QApplication.translate("Settings", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.portRandomiseButton.setText(QtGui.QApplication.translate("Settings", "Randomise", None, QtGui.QApplication.UnicodeUTF8))
        self.protocolTimeoutLabel.setText(QtGui.QApplication.translate("Settings", "Protocol Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.protocolTimeoutLineEdit.setToolTip(QtGui.QApplication.translate("Settings", "Idle time in seconds during protocol reads", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTransferLabel.setText(QtGui.QApplication.translate("Settings", "File Transfer Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTransferLineEdit.setToolTip(QtGui.QApplication.translate("Settings", "Idle time in seconds during file transfer protocol reads", None, QtGui.QApplication.UnicodeUTF8))
        self.chunkSizeLabel.setText(QtGui.QApplication.translate("Settings", "Transfer Chunk Size", None, QtGui.QApplication.UnicodeUTF8))
        self.chunkSizeDescriptionLabel.setText(QtGui.QApplication.translate("Settings", "Maximum bytes of data received before writing out to disk", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadLabel.setText(QtGui.QApplication.translate("Settings", "Download Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadLineEdit.setToolTip(QtGui.QApplication.translate("Settings", "Location to store incoming file transfers", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadButton.setText(QtGui.QApplication.translate("Settings", "       ", None, QtGui.QApplication.UnicodeUTF8))
        self.verifyCheckbox.setToolTip(QtGui.QApplication.translate("Settings", "Compute checksum on transfered file", None, QtGui.QApplication.UnicodeUTF8))
        self.verifyCheckbox.setText(QtGui.QApplication.translate("Settings", "Verify Downloads", None, QtGui.QApplication.UnicodeUTF8))
        self.fileRequestLimitLabel.setText(QtGui.QApplication.translate("Settings", "File Transfer Request", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTransferLimitSpinBox.setToolTip(QtGui.QApplication.translate("Settings", "Maximum days to keep request stored", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTransferRequestDaysLimitLabel.setText(QtGui.QApplication.translate("Settings", "days", None, QtGui.QApplication.UnicodeUTF8))
        self.friendRequestLimitLabel.setText(QtGui.QApplication.translate("Settings", "Friend Request", None, QtGui.QApplication.UnicodeUTF8))
        self.friendRequestLimitSpinBox.setToolTip(QtGui.QApplication.translate("Settings", "Maximum days to keep request stored", None, QtGui.QApplication.UnicodeUTF8))
        self.friendRequestLimitDaysLabel.setText(QtGui.QApplication.translate("Settings", "days", None, QtGui.QApplication.UnicodeUTF8))
        self.storageLabel.setText(QtGui.QApplication.translate("Settings", "Storage Encryption", None, QtGui.QApplication.UnicodeUTF8))
        self.encryptionDetailsLabel.setText(QtGui.QApplication.translate("Settings", "Salsa20 with Poly1305", None, QtGui.QApplication.UnicodeUTF8))
        self.keyLabel.setText(QtGui.QApplication.translate("Settings", "Public/Private Keys", None, QtGui.QApplication.UnicodeUTF8))
        self.keyDetailsLabel.setText(QtGui.QApplication.translate("Settings", "Curve25519", None, QtGui.QApplication.UnicodeUTF8))
        self.signatureLabel.setText(QtGui.QApplication.translate("Settings", "Digital Signature", None, QtGui.QApplication.UnicodeUTF8))
        self.signatureDetailsLabel.setText(QtGui.QApplication.translate("Settings", "Ed25519", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("Settings", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNetwork.setText(QtGui.QApplication.translate("Settings", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNetwork.setShortcut(QtGui.QApplication.translate("Settings", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStorage.setText(QtGui.QApplication.translate("Settings", "Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStorage.setShortcut(QtGui.QApplication.translate("Settings", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEncryption.setText(QtGui.QApplication.translate("Settings", "Encryption", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEncryption.setShortcut(QtGui.QApplication.translate("Settings", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))

from . import quip_qt_rc
