#
# List of country names and TLDs for flag icon reference
#

COUNTRIES = {'cyprus': 'cy', 'south sudan': 'ss', 'mozambique': 'mz', 'guernsey': 'gg', 'uruguay': 'uy',
             'antigua and barbuda': 'ag', 'turkey': 'tr', 'croatia': 'hr', 'botswana': 'bw', 'ghana': 'gh',
             'serbia': 'rs', 'portugal': 'pt', 'germany': 'de', 'san marino': 'sm', 'bangladesh': 'bd',
             'vietnam': 'vn', 'heard island': 'hm', 'mcdonald islands': 'hm', 'trinidad and tobago': 'tt',
             'kazakhstan': 'kz', 'belize': 'bz', 'venezuela': 've', 'montserrat': 'ms', 'somalia': 'so',
             'czech republic': 'cz', 'new caledonia': 'nc', 'oman': 'om', 'slovakia': 'sk', 'vanuatu': 'vu',
             'malawi': 'mw', 'nauru': 'nr', 'togo': 'tg', 'dominica': 'dm', 'zambia': 'zm',
             "people's republic of china": 'cn', 'egypt': 'eg', 'anguilla': 'ai', 'georgia': 'ge',
             'burkina faso': 'bf', 'djibouti': 'dj', 'romania': 'ro', 'lesotho': 'ls', 'united kingdom': 'uk',
             'england': 'uk', 'lebanon': 'lb', 'jamaica': 'jm', 'norfolk island': 'nf', 'tunisia': 'tn',
             'saint vincent and the grenadines': 'vc', 'montenegro': 'me', 'algeria': 'dz',
             'morocco': 'ma', 'ethiopia': 'et', 'moldova': 'md', 'austria': 'at', 'malta': 'mt', 'france': 'fr',
             'netherlands antilles': 'an', 'tajikistan': 'tj', 'brunei': 'bn', 'laos': 'la',
             'united states of america': 'us', 'usa': 'us', 'colombia': 'co', 'chile': 'cl', 'el salvador': 'sv',
             'wallis and futuna': 'wf', 'papua new guinea': 'pg', 'finland': 'fi', 'curaçao': 'cw', 'tonga': 'to',
             'brazil': 'br', 'bhutan': 'bt', 'yugoslavia': 'yu', 'jersey': 'je', 'sudan': 'sd',
             'turks and caicos islands': 'tc', 'greenland': 'gl', 'northern mariana islands': 'mp',
             'mayotte': 'yt', 'indonesia': 'id', 'luxembourg': 'lu', 'gibraltar': 'gi', 'hong kong': 'hk',
             'italy': 'it', 'poland': 'pl', 'saudi arabia': 'sa', 'saint lucia': 'lc', 'marshall islands': 'mh',
             'lithuania': 'lt', 'benin': 'bj', 'sierra leone': 'sl', 'singapore': 'sg', 'niue': 'nu',
             'cambodia': 'kh', 'canada': 'ca', 'federated states of micronesia': 'fm',
             'czechoslovakia': 'cs', 'mexico': 'mx', 'american samoa': 'as', 'libya': 'ly',
             'united states virgin islands': 'vi', 'cayman islands': 'ky', 'mali': 'ml', 'bahamas': 'bs',
             'angola': 'ao', 'rwanda': 'rw', 'mauritius': 'mu', 'cape verde': 'cv', 'saint helena': 'sh',
             'uganda': 'ug', 'hungary': 'hu', 'greece': 'gr', 'india': 'in', 'martinique': 'mq',
             'european union': 'eu', 'malaysia': 'my', 'peru': 'pe', 'british indian ocean territory': 'io',
             'swaziland': 'sz', 'macau': 'mo', 'french polynesia': 'pf', 'cocos islands': 'cc',
             'aruba': 'aw', 'central african republic': 'cf', 'cuba': 'cu', 'svalbard and': 'sj', 'haiti': 'ht',
             'nepal': 'np', 'kiribati': 'ki', 'new zealand': 'nz', 'réunion': 're', 'east timor': 'tp',
             'sweden': 'se', 'estonia': 'ee', 'panama': 'pa', 'qatar': 'qa', 'fiji': 'fj', 'syria': 'sy',
             'state of palestine': 'ps', 'guinea-bissau': 'gw', 'kenya': 'ke', 'barbados': 'bb',
             'comoros': 'km', 'norway': 'no', 'philippines': 'ph', 'tuvalu': 'tv', 'falkland islands': 'fk',
             'south georgia and the south sandwich islands': 'gs', 'monaco': 'mc', 'senegal': 'sn',
             'french guiana': 'gf', "côte d'ivoire": 'ci', 'vatican city': 'va', 'netherlands': 'nl',
             'palau': 'pw', 'republic of korea': 'kr', 'sri lanka': 'lk', 'australia': 'au', 'albania': 'al',
             'sint maarten': 'sx', 'gabon': 'ga', 'zimbabwe': 'zw', 'guatemala': 'gt', 'maldives': 'mv',
             'niger': 'ne', 'thailand': 'th', 'kyrgyzstan': 'kg', 'republic of the congo': 'cg',
             'saint kitts and nevis': 'kn', 'bulgaria': 'bg', 'united arab emirates': 'ae', 'taiwan': 'tw',
             'antarctica': 'aq', 'jolly': 'jolly', 'puerto rico': 'pr', 'faroe islands': 'fo',
             'democratic republic of the congo': 'cd', 'congo': 'cd', 'bouvet island': 'bv', 'turkmenistan': 'tm',
             'soviet union': 'su', 'japan': 'jp', 'lgbt': 'lgbt', 'the gambia': 'gm', 'ukraine': 'ua',
             'bosnia': 'ba', 'herzegovina': 'ba', 'cook islands': 'ck', 'french southern and antarctic lands': 'tf',
             'grenada': 'gd', 'south africa': 'za', 'russia': 'ru', 'guinea': 'gn', 'ecuador': 'ec',
             'myanmar': 'mm', 'chad': 'td', 'tanzania': 'tz', 'liechtenstein': 'li', 'kuwait': 'kw',
             'liberia': 'lr', 'são tomé and príncipe': 'st', 'uzbekistan': 'uz', 'bahrain': 'bh',
             'ascension island': 'ac', 'suriname': 'sr', 'pitcairn islands': 'pn', 'tokelau': 'tk',
             'bolivia': 'bo', "democratic people's republic of korea": 'kp', 'switzerland': 'ch',
             'latvia': 'lv', 'andorra': 'ad', 'eritrea': 'er', 'guyana': 'gy', 'dominican republic': 'do',
             'armenia': 'am', 'yemen': 'ye', 'spain': 'es', 'slovenia': 'si', 'azerbaijan': 'az',
             'israel': 'il', 'western sahara': 'eh', 'samoa': 'ws', 'east germany': 'dd', 'paraguay': 'py',
             'christmas island': 'cx', 'solomon islands': 'sb', 'cameroon': 'cm', 'burundi': 'bi', 'zaire': 'zr',
             'macedonia': 'mk', 'iraq': 'iq', 'afghanistan': 'af', 'guam': 'gu', 'bermuda': 'bm', 'belgium': 'be',
             'british virgin islands': 'vg', 'jordan': 'jo', 'isle of man': 'im', 'seychelles': 'sc',
             'iceland': 'is', 'argentina': 'ar', 'saint-pierre and miquelon': 'pm', 'belarus': 'by',
             'pakistan': 'pk', 'guadeloupe': 'gp', 'honduras': 'hn', 'costa rica': 'cr', 'iran': 'ir',
             'mauritania': 'mr', 'mongolia': 'mn', 'nigeria': 'ng', 'ireland': 'ie', 'nicaragua': 'ni',
             'åland': 'ax', 'namibia': 'na', 'madagascar': 'mg', 'denmark': 'dk', 'equatorial guinea': 'gq',
             'scotland': 'sco', 'wales': 'wales'}
